apiVersion: v1
kind: Service
metadata:
  name: capston-service
spec:
  selector:
    app: reactapp
  ports:
    - port: 8000 #arbitrary port
      targetPort: 3000 #application port
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capston-deployment
  labels:
    app: reactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: capston-pod-reactapp
        image: wardahsana/caps
        ports:
        - containerPort: 3000
        resources:
      limits:
        memory: 512Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"