apiVersion: v1
kind: Service
metadata:
  name: capston-service
spec:
  selector:
    app: reactapp
  ports:
    - port: 8000 #arbitrary port
      targetPort: 3000 #application port
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capston-deployment
  labels:
    app: reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: capston-pod-reactapp
        image: wardahsana/capstone
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
   
    